version: '3'
services:
  sokroza:
    image: sokroza_nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3227:3000
    networks:
      - data_analytics
networks:
  data_analytics:
    external: true 
